### ISSUE TITLE
Print Multiple copies using IXPSPrintJob(XpsPrint.dll) or How to apply PrinterSettings to IXPSPrintJob(XpsPrint.dll)

### ISSUE THREAD

**Issue by Lucky-M** [asposewords/Aspose_Words_NET#4]
Hi,

   I am using your code given on the below link to print documents of type Aspose.Word.Document class using XPSPrint.dll by calling its StartJob and CopyJob methods. It is working fine for me as soon as i am printing a single copy of the document. But I am not able to print multiple copies of the document using the same Job. I am able to get those printer settings from PrintDialog window but i dont know how to apply those Printer Settings when printing via XPSPrintJob.dll.

I used this link:

https://github.com/asposewords/Aspose_Words_NET/blob/master/RenderingAndPrinting/PrintDocument/XpsPrint/CSharp/XpsPrintHelper.cs

Can you please suggest me how to resolve this problem.

Many thanks in advance.

Regards
Lucky

**Comment by muhammad-ijaz** [comment]
Same issue is reported in Aspose forums and logged. You will be updated once the issue is resolved.

**Comment by muhammad-ijaz** [comment]
The method StartJob() is taken from Microsoft Printing API https://msdn.microsoft.com/en-us/library/windows/desktop/dd374437%28v=vs.85%29.aspx. It does not take any argument like "NoOfCopies". Unfortunately, we see no way to help you using XpsPrint API but may be you can use Document.Print method as it says in article:

The Document object provides a family of the Print methods to print documents and these methods print via the .NET printing classes defined in the System.Drawing.Printing namespace. 

There are many customers of Aspose.Words who use this printing method in their server-side applications without any problems so it is possible to print multiple copies of the document using Print method.

**Comment by muhammad-ijaz** [comment]
Aspose forum link for reference.

**Comment by muhammad-ijaz** [comment]
As a workaround, you can append the document with itself to print multiple copies of the same document in a single job. Please check http://www.aspose.com/docs/display/wordsnet/Join+a+Document+onto+another+Document for more details on how to append documents.
